### ISSUE TITLE
Protocol 2.1

### ISSUE THREAD

**Issue by michelinok** [Erriez/ErriezOregonTHN128#16]
### Feature request

Add protocol 2.1, it would be great!!!!!

### Hardware setup

Arduino or esp

### Is your feature request related to a problem?

no

### Describe the solution you'd like

Implementing the 2.1 oregon protocol

### Checks

- [X] I understand that this library is maintained by volunteers in spare time. Response time may vary.

### Export restrictions.

- [X] I accept [End User Agreement](https://github.com/Erriez/ErriezOregonTHN128/blob/master/END_USER_AGREEMENT.md).

**Comment by Erriez** [comment]
Thanks for creating this feature request. I've designed this library specifically for one device which is v1 protocol by reverse engineering as there was no Arduino library available.

Do you have a specific device type and protocol documentation? Unfortunately, I do not have devices with protocol v2.1 for development / testing.

**Comment by michelinok** [comment]
Hi Erriez
no...I don't own any Oregon v2.1 devices but you can find a lot of documentation about that protocol, just google (all the results will point you to the same website...).
Anyway no problem...I'm just learning protocols/encoding/decoding just for fun.

**Comment by Erriez** [comment]
Closing ticket, insufficient information / test devices.

**Comment by LeJiPe** [comment]
J'ai réalisé une sonde compatible Oregon THN132N  qui fonctionne intégralement. (checksum et CRC2) testée avec le récepteur Oregon BAR626. https://github.com/LeJiPe/Oregon-THN132N-Reverse-Engineering/tree/main
